/*
 * Generated by dtrace(1M).
 */

#ifndef	_PERLDTRACE_H_IN
#define	_PERLDTRACE_H_IN

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#include <sys/sdt.h>

#if _DTRACE_VERSION

#define	PERL_LOADED_FILE(arg0) \
	__dtrace_perl___loaded__file(arg0)
#ifndef	__sparc
#define	PERL_LOADED_FILE_ENABLED() \
	__dtraceenabled_perl___loaded__file()
#else
#define	PERL_LOADED_FILE_ENABLED() \
	__dtraceenabled_perl___loaded__file(0)
#endif
#define	PERL_LOADING_FILE(arg0) \
	__dtrace_perl___loading__file(arg0)
#ifndef	__sparc
#define	PERL_LOADING_FILE_ENABLED() \
	__dtraceenabled_perl___loading__file()
#else
#define	PERL_LOADING_FILE_ENABLED() \
	__dtraceenabled_perl___loading__file(0)
#endif
#define	PERL_OP_ENTRY(arg0) \
	__dtrace_perl___op__entry(arg0)
#ifndef	__sparc
#define	PERL_OP_ENTRY_ENABLED() \
	__dtraceenabled_perl___op__entry()
#else
#define	PERL_OP_ENTRY_ENABLED() \
	__dtraceenabled_perl___op__entry(0)
#endif
#define	PERL_PHASE_CHANGE(arg0, arg1) \
	__dtrace_perl___phase__change(arg0, arg1)
#ifndef	__sparc
#define	PERL_PHASE_CHANGE_ENABLED() \
	__dtraceenabled_perl___phase__change()
#else
#define	PERL_PHASE_CHANGE_ENABLED() \
	__dtraceenabled_perl___phase__change(0)
#endif
#define	PERL_SUB_ENTRY(arg0, arg1, arg2, arg3) \
	__dtrace_perl___sub__entry(arg0, arg1, arg2, arg3)
#ifndef	__sparc
#define	PERL_SUB_ENTRY_ENABLED() \
	__dtraceenabled_perl___sub__entry()
#else
#define	PERL_SUB_ENTRY_ENABLED() \
	__dtraceenabled_perl___sub__entry(0)
#endif
#define	PERL_SUB_RETURN(arg0, arg1, arg2, arg3) \
	__dtrace_perl___sub__return(arg0, arg1, arg2, arg3)
#ifndef	__sparc
#define	PERL_SUB_RETURN_ENABLED() \
	__dtraceenabled_perl___sub__return()
#else
#define	PERL_SUB_RETURN_ENABLED() \
	__dtraceenabled_perl___sub__return(0)
#endif


extern void __dtrace_perl___loaded__file(const char *);
#ifndef	__sparc
extern int __dtraceenabled_perl___loaded__file(void);
#else
extern int __dtraceenabled_perl___loaded__file(long);
#endif
extern void __dtrace_perl___loading__file(const char *);
#ifndef	__sparc
extern int __dtraceenabled_perl___loading__file(void);
#else
extern int __dtraceenabled_perl___loading__file(long);
#endif
extern void __dtrace_perl___op__entry(const char *);
#ifndef	__sparc
extern int __dtraceenabled_perl___op__entry(void);
#else
extern int __dtraceenabled_perl___op__entry(long);
#endif
extern void __dtrace_perl___phase__change(const char *, const char *);
#ifndef	__sparc
extern int __dtraceenabled_perl___phase__change(void);
#else
extern int __dtraceenabled_perl___phase__change(long);
#endif
extern void __dtrace_perl___sub__entry(const char *, const char *, int, const char *);
#ifndef	__sparc
extern int __dtraceenabled_perl___sub__entry(void);
#else
extern int __dtraceenabled_perl___sub__entry(long);
#endif
extern void __dtrace_perl___sub__return(const char *, const char *, int, const char *);
#ifndef	__sparc
extern int __dtraceenabled_perl___sub__return(void);
#else
extern int __dtraceenabled_perl___sub__return(long);
#endif

#else

#define	PERL_LOADED_FILE(arg0)
#define	PERL_LOADED_FILE_ENABLED() (0)
#define	PERL_LOADING_FILE(arg0)
#define	PERL_LOADING_FILE_ENABLED() (0)
#define	PERL_OP_ENTRY(arg0)
#define	PERL_OP_ENTRY_ENABLED() (0)
#define	PERL_PHASE_CHANGE(arg0, arg1)
#define	PERL_PHASE_CHANGE_ENABLED() (0)
#define	PERL_SUB_ENTRY(arg0, arg1, arg2, arg3)
#define	PERL_SUB_ENTRY_ENABLED() (0)
#define	PERL_SUB_RETURN(arg0, arg1, arg2, arg3)
#define	PERL_SUB_RETURN_ENABLED() (0)

#endif


#ifdef	__cplusplus
}
#endif

#endif	/* _PERLDTRACE_H_IN */
